apiVersion: v1
kind: Pod
metadata:
  name: bench
spec:
  containers:
  - name: bench
    # image: gcr.io/shopify-docker-images/ci-branches/cloud/rust-bench-tcp:latest
    # image: gcr.io/shopify-docker-images/ci-branches/cloud/rust-bench-unix:latest
    image: gcr.io/shopify-docker-images/ci-branches/cloud/ruby-bench-unix:latest
    # image: gcr.io/shopify-docker-images/ci-branches/cloud/ruby-bench-tcp:latest
    volumeMounts:
    - name: memcached
      mountPath: /var/run/memcached
    resources:
      requests:
        memory: "128Mi"
        cpu: 1
      limits:
        memory: "512Mi"
  - name: memcached
    image: memcached:latest
    # ports:
    # - containerPort: 11211
    command: ["memcached", "-s", "/var/run/memcached/memcached.sock", "-a", "0666"]
    volumeMounts:
    - name: memcached
      mountPath: /var/run/memcached
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
  volumes:
  - name: memcached
    emptyDir: {}
